### ISSUE TITLE
gradle not available(?)

### ISSUE THREAD

**Issue by Phoscur** [marcomaisel/docker-ionic#3]
I noticed when using this and actually also with other images, which I tried to use as a base in gitlab ci, gradle is not available and `gradle -v` fails
So I'm installing it again in my before_script:
```
 before_script:
    - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;26.0.2" "platforms;android-26" "platform-tools"
    #- gradle -v for some reason gradle is not installed
    - wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
    - mkdir $CI_PROJECT_DIR/gradle
    - unzip -d $CI_PROJECT_DIR/gradle gradle-4.10.3-bin.zip
    - export PATH=$PATH:$CI_PROJECT_DIR/gradle/gradle-4.10.3/bin
    - cd $CI_PROJECT_DIR
```
Same for sdkmanager, should that one also be available?
Any ideas?

**Comment by marcomaisel** [comment]
I can't help you with your problem but I managed to fix the problems with building the docker image on dockerhub. I merged all your commits and it should be working now

**Comment by Phoscur** [comment]
Thank you for updating! I should be able to remove the line accepting the new android 26 sdk. I'm closing this since the problem is not specific to this image.
