### ISSUE TITLE
Cannot use docker image for ionic 3 android build

### ISSUE THREAD

**Issue by nickwinger** [marcomaisel/docker-ionic#5]
Hi,

i want to use your docker image for ionic 3 android build.
However i get an error with leveldown:
`
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^
leveldown.target.mk:119: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/builds/nickwinger/urano/node_modules/leveldown/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/builds/nickwinger/urano/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! stack     at ChildProcess.emit (events.js:182:13)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/builds/nickwinger/urano/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! build     at ChildProcess.emit (events.js:182:13)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
`
Do you have any ideas what the problem could be ?
Do you have a sample gitlab yaml where you build your Ionic 3 App ?

Of course the build works on my local pc.

Cheers,
Nick

**Comment by nickwinger** [comment]
I just resolved the issue myself, with a fork from your image:
thebit4bit/ionic3:latest

I'm using node 8 instead of 10, then the level-down works.
I guess it's better to have an older version of node for ionic 3 as a lot of older libraries depend on older node, and ionic 3 is not the newest anymore ;)

**Comment by marcomaisel** [comment]
You're probably right about that. I updated the node version from 9 to 10 because of a request from someone else lately. Thinking about setting it back to 9.
